FIREBASE_AUTH_REST_SIGN_IN = (
    "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword"
)

RESPONSE_MSG_REGISTER_SUCCESS = "User registered successfully."
RESPONSE_MSG_LOGIN_SUCCESS = "Logged in successfully."
RESPONSE_MSG_INVALID_CREDENTIALS = "Invalid email or password."
RESPONSE_MSG_REGISTRATION_FAILED = "Unable to complete registration."

FIREBASE_ERROR_EMAIL_EXISTS = "EMAIL_EXISTS"
FIREBASE_ERROR_INVALID_PASSWORD = "INVALID_PASSWORD"
FIREBASE_ERROR_EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
FIREBASE_ERROR_INVALID_LOGIN = "INVALID_LOGIN_CREDENTIALS"
