FIREBASE_AUTH_REST_SIGN_IN = (
    "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword"
)

EMAIL_REGEX = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"
DISPLAY_NAME_REGEX = r"^[A-Za-z ]+$"
PASSWORD_REGEX = r"^(?=.*[A-Za-z])(?=.*\d).+$"

FIREBASE_ERROR_EMAIL_EXISTS = "EMAIL_EXISTS"
FIREBASE_ERROR_INVALID_PASSWORD = "INVALID_PASSWORD"
FIREBASE_ERROR_EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
FIREBASE_ERROR_INVALID_LOGIN = "INVALID_LOGIN_CREDENTIALS"
