FIREBASE_TIMEOUT_SECONDS = 10

TOKEN_CLAIM_ROLE = "role"

DEFAULT_BALANCE = 1000
DEFAULT_CURRENCY = {"code": "INR", "symbol": "₹"}

MAX_IMAGE_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024
SIGNED_UPLOAD_URL_EXPIRY_MINUTES = 15

DEFAULT_PAGINATION_LIMIT = 20
MIN_PAGINATION_LIMIT = 1
MAX_PAGINATION_LIMIT = 50

TIMEZONE = "Asia/Kolkata"
