FIREBASE_TIMEOUT_SECONDS = 10

TOKEN_CLAIM_ROLE = "role"

DEFAULT_BALANCE = 1000
DEFAULT_CURRENCY = {"code": "INR", "symbol": "₹"}

MAX_IMAGE_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024
SIGNED_UPLOAD_URL_EXPIRY_MINUTES = 15

DUPLICATE_NAME_CHECK_LIMIT = 2

DEFAULT_PAGINATION_LIMIT = 20
MIN_PAGINATION_LIMIT = 1
MAX_PAGINATION_LIMIT = 50

RESPONSE_MSG_HEALTH_OK = "OK"
RESPONSE_MSG_MISSING_FIELDS = "Required fields are missing."
RESPONSE_MSG_FORBIDDEN = "You do not have permission to access this resource."
RESPONSE_MSG_INTERNAL_ERROR = "An unexpected error occurred."
